ex13_library
AnaBelochka/external-courses pull request #16
Opened 2019-05-05 12:11 UTC by AnaBelochka

I completed first task for library, where I parsed json-file and displayed it

2019-05-05 16:12 UTC, eugrdn commented
<img width="1438" alt="Screenshot 2019-05-05 at 19 00 07" src="https://user-images.githubusercontent.com/16277984/57196782-ee7d9400-6f68-11e9-9e84-eb4580c1cf7a.png">
Доделать:
1. убрать отступы снизу и сбоку (используй относительные величины для ширины/высоты контейнера)
2. прижать футер к низу страницы
3. скролл только внутри блока с книгами и историей
4. нужно показывать и пустые звездочки тоже
5*. можешь в этой же ветке сделать обработчки установки рейтинга

2019-05-29 10:13 UTC, AnaBelochka commented
Не сделала историю. Посмотри, пожалуйста, 14 домашку)

2019-05-29 18:38 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +View.prototype.isNumeric = function (n) {
вынеси в глобальные утилиты

2019-05-29 18:39 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +    if (elems.cost.parentNode.lastChild.className === "errorMessage") this.deleteErrorMsg(elems.cost.parentNode);
без `{}` не читаемо, добавь везде 👍

2019-05-29 18:51 UTC, eugrdn requested changes
Удаляй все `binded...` функции, и self = this, в твоей реалиации все привязки происходят в одном месте -- в функции events

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +        bindedReturnBooks = self.controller.bind(self.controller.returnBooks, self),
зачем создавать функцию только для одного вызова? у тебя есть .call, .apply

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +        self = this,
в этой функции this будет объктом, раз ты ее привязала выше, где отправляла в обработчик,  то же касается bindedReturnBooks

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +        self = this,
убери все self из нее

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +View.prototype.changeStyle = function (isClicked) {
changeFilterStyle/Color

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.bind = function (func, context) {
лишняя функция, единственное, где тебе нужна привязка -- это там где навешиваешь обработчики на события, там вполне можно воспользоваться обычным `.bind`

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +        self = this;
этот случай работает только если у тебя self сохраняется в замыкании, здесь ты записываешь this, и сразу же его используешь, у тебя работает только потому, что саму handleInput ты уже привязала в  функции `events`

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +        self.controller.model.state.asideFilter = "must_read";
self.controller.model.state.asideFilter -> this.controller.setAsideFilter()

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +    return books.filter(function(element) {
`.find`

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +    var self = this;
это бессмысленно

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/utils/callApi.js
> +    // var model = this;
удали комментарий

2019-05-29 18:51 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +View.prototype.events = function () {
что за странное название функции, должен быть глагол

2019-05-29 19:27 UTC, AnaBelochka commented on src/ex13_library/src/views/view.js
> +        bindedReturnBooks = self.controller.bind(self.controller.returnBooks, self),
хорошо, тогда удалю bind вообще

2019-05-29 21:14 UTC, AnaBelochka commented on src/ex13_library/src/controllers/controller.js
> +    return books.filter(function(element) {
Жень, я не совсем поняла зачем использовать find? Он же возвращает первый правильный, а нам нужны все книги этой категории?

2019-05-31 14:06 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +    return books.filter(function(element) {
это можно заменить на find
`
      for (let index = 0; index < element.categories.length; index++) {
                if (element.categories[index] === filter) {
                    return true;
                }
            }
`

2019-06-02 13:59 UTC, eugrdn requested changes

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.returnBooks = function () {
getBooks

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.pushBook = function (book) {
addBook

зачем комментарии, которые не нужны, если назвать метод правильно

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +    var inputValue = event.target.value;
это нужно передавать аргументом сразу, а доставать из event во view

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.clickAsideFilter = function (event) {
click это действие view, здесь handle или пр.

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +                if (el === filter) {
достаточно => el === filter

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +                if (el === filter) {
не понятно какой блок к какому отностится, вынеси результат find в переменную

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.clickFilterAll = function (event) {
event.preventDefault(); должно быть во view

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/controllers/controller.js
> +Controller.prototype.clickAsideFilter = function (event) {
event.preventDefault(); должно быть во view

2019-06-02 13:59 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +View.prototype.addEvents = function () {
не events, а listeners/eventListeners/eventHandlers

2019-06-02 17:29 UTC, AnaBelochka commented on src/ex13_library/src/controllers/controller.js
> +                if (el === filter) {
достаточно => el === filter

2019-06-03 07:42 UTC, eugrdn commented on src/ex13_library/src/views/view.js
> +        this.controller.handleFilterAll.bind(this);
1. bind возвращает новую функцию, а не вызывает ее
2. у тебя стрелочная функция, те здесь будет тот же контекст, что и снаружи

2019-06-03 14:19 UTC, merged